import { config } from 'dotenv';
config({ path: '.env' });
import { generateComponent } from './src/lib/agents/pipeline/runner';
import * as fs from 'fs';
import * as path from 'path';

async function generateOlympusHomePage() {
  console.log('🏠 OLYMPUS: Generating Complete Home Page Showcase');

  const homePagePrompt = `
Create a complete Next.js home page component that showcases OLYMPUS AI capabilities.

REQUIREMENTS:
- Component Name: OlympusShowcase
- Framework: Next.js 14 + React 18 + TypeScript
- Styling: Tailwind CSS with glassmorphism design
- Layout: Professional landing page structure

CONTENT SECTIONS:
1. Hero Section:
   - "OLYMPUS 3.0" title with gradient text
   - "38 AI Agents Working Together" subtitle
   - Professional tagline about AI development
   - Call-to-action button

2. Features Grid:
   - 3 feature cards showcasing AI capabilities
   - Icons, titles, descriptions
   - Glassmorphism cards with hover effects

3. Statistics Section:
   - Key metrics (38 agents, real AI integration, production ready)
   - Animated counters or progress bars

4. Generated Components Showcase:
   - Display sections for marketing page, pricing cards, data table
   - Each with title, description, and live component embed
   - Use dynamic imports for the generated components

5. Technology Stack:
   - Showcase the tech behind OLYMPUS
   - OpenAI, Next.js, TypeScript, etc.

6. Footer:
   - OLYMPUS branding
   - Links to generated components
   - Status indicators

DESIGN REQUIREMENTS:
- Dark theme with purple/blue gradients
- Glassmorphism effects throughout
- Responsive mobile-first design
- Smooth animations and transitions
- Professional typography
- Accessibility compliant

FUNCTIONALITY:
- Import and display the actual generated components
- Dynamic loading with proper error handling
- Clean, maintainable TypeScript code
- Production-ready component structure

Make this the perfect showcase for OLYMPUS AI generation capabilities.
`;

  console.log('🤖 Handing over to OLYMPUS agents...');

  const result = await generateComponent(homePagePrompt, {
    framework: 'react',
    targetScore: 100,
    maxIterations: 3,
    enableRAG: false,
  });

  console.log('\n✅ OLYMPUS Home Page Generated!');
  console.log('📦 Component:', result.filename);
  console.log('📏 Size:', result.code.length, 'characters');
  console.log('🎖️ Quality:', result.review?.score || 'Unknown');

  // Save as the main home page
  const homePagePath = path.join(process.cwd(), 'src', 'app', 'page.tsx');
  fs.writeFileSync(homePagePath, result.code);

  console.log('💾 Installed as main home page: src/app/page.tsx');
  console.log('\n🚀 OLYMPUS is now fully autonomous!');
  console.log('The home page was generated by AI agents, not manual coding.');

  return result;
}

generateOlympusHomePage();
