/**
 * GENERATED BY: ENGINE Agent
 * Task service - business logic for task operations
 */

export interface Task {
  id: string;
  title: string;
  completed: boolean;
  category?: string;
  userId: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateTaskInput {
  title: string;
  category?: string;
  userId: string;
}

export interface UpdateTaskInput {
  title?: string;
  completed?: boolean;
  category?: string;
}

// In-memory store for testing (would use Supabase in production)
let tasks: Task[] = [];

export const taskService = {
  /**
   * Create a new task
   */
  async create(input: CreateTaskInput): Promise<Task> {
    if (!input.title || input.title.trim().length === 0) {
      throw new Error('Task title is required');
    }

    if (input.title.length > 500) {
      throw new Error('Task title must be less than 500 characters');
    }

    const task: Task = {
      id: `task_${Date.now()}_${Math.random().toString(36).slice(2)}`,
      title: input.title.trim(),
      completed: false,
      category: input.category,
      userId: input.userId,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    tasks.push(task);
    return task;
  },

  /**
   * Get all tasks for a user
   */
  async getByUser(userId: string): Promise<Task[]> {
    return tasks.filter(t => t.userId === userId);
  },

  /**
   * Get a single task by ID
   */
  async getById(id: string): Promise<Task | null> {
    return tasks.find(t => t.id === id) || null;
  },

  /**
   * Update a task
   */
  async update(id: string, input: UpdateTaskInput): Promise<Task> {
    const index = tasks.findIndex(t => t.id === id);
    if (index === -1) {
      throw new Error('Task not found');
    }

    tasks[index] = {
      ...tasks[index],
      ...input,
      updatedAt: new Date(),
    };

    return tasks[index];
  },

  /**
   * Toggle task completion
   */
  async toggle(id: string): Promise<Task> {
    const task = await this.getById(id);
    if (!task) {
      throw new Error('Task not found');
    }

    return this.update(id, { completed: !task.completed });
  },

  /**
   * Delete a task
   */
  async delete(id: string): Promise<void> {
    const index = tasks.findIndex(t => t.id === id);
    if (index === -1) {
      throw new Error('Task not found');
    }

    tasks.splice(index, 1);
  },

  /**
   * Clear all tasks (for testing)
   */
  async clear(): Promise<void> {
    tasks = [];
  },
};

export default taskService;
