/**
 * GENERATED BY: JUNIT Agent
 * Unit tests for task service
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { taskService } from './task-service';

describe('TaskService', () => {
  beforeEach(async () => {
    await taskService.clear();
  });

  describe('create', () => {
    it('should create a task with valid input', async () => {
      const task = await taskService.create({
        title: 'Test task',
        userId: 'user_123',
      });

      expect(task.id).toBeDefined();
      expect(task.title).toBe('Test task');
      expect(task.completed).toBe(false);
      expect(task.userId).toBe('user_123');
    });

    it('should throw error for empty title', async () => {
      await expect(
        taskService.create({ title: '', userId: 'user_123' })
      ).rejects.toThrow('Task title is required');
    });

    it('should throw error for title exceeding 500 chars', async () => {
      const longTitle = 'a'.repeat(501);
      await expect(
        taskService.create({ title: longTitle, userId: 'user_123' })
      ).rejects.toThrow('Task title must be less than 500 characters');
    });

    it('should include category if provided', async () => {
      const task = await taskService.create({
        title: 'Test task',
        category: 'Work',
        userId: 'user_123',
      });

      expect(task.category).toBe('Work');
    });
  });

  describe('getByUser', () => {
    it('should return tasks for a specific user', async () => {
      await taskService.create({ title: 'Task 1', userId: 'user_123' });
      await taskService.create({ title: 'Task 2', userId: 'user_123' });
      await taskService.create({ title: 'Task 3', userId: 'user_456' });

      const tasks = await taskService.getByUser('user_123');

      expect(tasks.length).toBe(2);
      expect(tasks.every(t => t.userId === 'user_123')).toBe(true);
    });

    it('should return empty array for user with no tasks', async () => {
      const tasks = await taskService.getByUser('nonexistent');
      expect(tasks).toEqual([]);
    });
  });

  describe('toggle', () => {
    it('should toggle task completion status', async () => {
      const task = await taskService.create({ title: 'Test', userId: 'user_123' });
      expect(task.completed).toBe(false);

      const toggled = await taskService.toggle(task.id);
      expect(toggled.completed).toBe(true);

      const toggledAgain = await taskService.toggle(task.id);
      expect(toggledAgain.completed).toBe(false);
    });

    it('should throw error for non-existent task', async () => {
      await expect(
        taskService.toggle('nonexistent')
      ).rejects.toThrow('Task not found');
    });
  });

  describe('delete', () => {
    it('should delete a task', async () => {
      const task = await taskService.create({ title: 'Test', userId: 'user_123' });
      await taskService.delete(task.id);

      const found = await taskService.getById(task.id);
      expect(found).toBeNull();
    });

    it('should throw error for non-existent task', async () => {
      await expect(
        taskService.delete('nonexistent')
      ).rejects.toThrow('Task not found');
    });
  });
});
