/**
 * Create a build with GUARANTEED working code
 */
import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';

async function main() {
  // Load env
  const envPath = path.join(process.cwd(), '.env.local');
  if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf-8');
    for (const line of envContent.split('\n')) {
      const [key, ...valueParts] = line.split('=');
      if (key && valueParts.length) {
        process.env[key.trim()] = valueParts.join('=').trim();
      }
    }
  }

  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );

  // Find a project
  const { data: projects } = await supabase.from('projects').select('id, name, tenant_id').limit(1);
  if (!projects?.length) {
    console.error('No projects found');
    return;
  }
  const project = projects[0];
  console.log(`Using project: ${project.name}`);

  // Create build
  const { data: build, error } = await supabase.from('builds').insert({
    project_id: project.id,
    tenant_id: project.tenant_id,
    tier: 'starter',
    status: 'completed',
    progress: 100,
    prompt: 'Test build with working code',
    completed_at: new Date().toISOString()
  }).select().single();

  if (error) {
    console.error('Failed to create build:', error.message);
    return;
  }

  console.log(`Created build: ${build.id}`);

  // GUARANTEED WORKING CODE
  const appTsx = `import { useState } from 'react';

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500">
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-md mx-auto bg-white rounded-2xl shadow-2xl overflow-hidden">
          <div className="bg-gradient-to-r from-indigo-600 to-purple-600 px-6 py-8">
            <h1 className="text-3xl font-bold text-white text-center">
              🚀 OLYMPUS Works!
            </h1>
            <p className="text-indigo-100 text-center mt-2">
              AI-Generated Preview
            </p>
          </div>

          <div className="px-6 py-8">
            <div className="text-center">
              <div className="text-6xl font-bold text-indigo-600 mb-4">
                {count}
              </div>
              <p className="text-gray-500 mb-6">Click the button to increment</p>

              <div className="flex gap-3 justify-center">
                <button
                  onClick={() => setCount(c => c + 1)}
                  className="px-6 py-3 bg-indigo-600 text-white font-semibold rounded-lg hover:bg-indigo-700 transition-colors shadow-lg hover:shadow-xl"
                >
                  + Add One
                </button>
                <button
                  onClick={() => setCount(0)}
                  className="px-6 py-3 bg-gray-200 text-gray-700 font-semibold rounded-lg hover:bg-gray-300 transition-colors"
                >
                  Reset
                </button>
              </div>
            </div>

            <div className="mt-8 pt-6 border-t border-gray-200">
              <p className="text-center text-sm text-gray-400">
                Build ID: ${build.id.slice(0, 8)}
              </p>
              <p className="text-center text-xs text-gray-300 mt-1">
                Generated by OLYMPUS 2.0
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}`;

  const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>OLYMPUS Preview</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
  <div id="root"></div>
</body>
</html>`;

  const indexTsx = `import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './index.css';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>
);`;

  const indexCss = `@tailwind base;
@tailwind components;
@tailwind utilities;`;

  const artifacts = [
    { type: 'code', path: '/App.tsx', content: appTsx, language: 'tsx' },
    { type: 'code', path: '/index.html', content: indexHtml, language: 'html' },
    { type: 'code', path: '/index.tsx', content: indexTsx, language: 'tsx' },
    { type: 'code', path: '/index.css', content: indexCss, language: 'css' },
  ];

  // Store artifacts
  const { error: insertError } = await supabase.from('build_agent_outputs').insert({
    build_id: build.id,
    agent_id: 'code-generator',
    status: 'completed',
    artifacts: artifacts
  });

  if (insertError) {
    console.error('Failed to store artifacts:', insertError.message);
    return;
  }

  console.log('\n✅ BUILD CREATED WITH WORKING CODE!');
  console.log(`\n🔗 Preview URL: http://localhost:3000/builds/${build.id}/preview`);
  console.log(`\n📋 Build ID: ${build.id}`);
}

main().catch(console.error);
